<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-6UHVP5N" name="com.CucumberRunner" tests="1" failures="0" timestamp="2020-08-05T11:32:22 IST" time="19.194" errors="1">
  <testcase name="scenario" time="19.194" classname="com.CucumberRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.maveric.core.utils.web.WebActions.logScreenshot(WebActions.java:23)
at com.maveric.core.testng.listeners.DriverListener.takeFailureScreenshot(DriverListener.java:58)
at com.maveric.core.testng.listeners.DriverListener.afterInvocation(DriverListener.java:41)
at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:60)
at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:631)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- scenario -->
  <system-out/>
</testsuite> <!-- com.CucumberRunner -->
